### ISSUE TITLE
MyBatis配置可以修改为注解形式

### ISSUE THREAD

**Issue by zjy4fun** [BreakingAwful/chatting#11]

**Comment by Crazyokd** [comment]
为了方便以后可能出现的复杂 sql 语句编写，我是刻意使用配置文件的。

**Comment by zjy4fun** [comment]
@Crazyokd 哦，我还以为升级到springboot就要采用全注解开发呢，用xml写复杂sql应该更方便一些，其实咋写都行，那我就关掉这个issue了
