### ISSUE TITLE
配置文件可以进行拆分管理

### ISSUE THREAD

**Issue by zjy4fun** [BreakingAwful/chatting#12]
可以分为：
- application.yml
- application-dev.yml
- application-pro.yml

另外本地的文件上传目录名可以通过命令行的方式追加，不需要写进配置文件，这样大家开发的时候就可以使用同一套配置文件了

参考：https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/features.html#features.profiles

#Crazyokd

**Comment by Crazyokd** [comment]
1. 配置文件包含这个我是知道的，但是目前的体量拆分配置文件无疑弊大于利。
2. 本地的文件上传目录通过命令行追加真不见得比配置文件配置来的方便。

**Comment by zjy4fun** [comment]
嗯嗯，写进issue的东西不一定都要照做，只是放在这里留个优化的方向
觉得不合理可以直接讨论，然后关掉

**Comment by zjy4fun** [comment]
我们公司的项目对这种配置文件一般有两种处理方式：
1. 每个人创建自己的配置文件，覆盖掉公共的配置文件内容，然后将自己的配置文件加进.gitignore
2. 不修改公共的配置文件，然后使用命令行追加的方式进行覆盖

这两种方式无非就是让所有人使用同一套代码配置，合作起来更加方便。
当然开源项目可以随便写写了，我只是给个优化的思路，也不一定合理，大家可以一起讨论嘛😆
